name: downloader3
description: "Downloader<3 — Android-Begleit-App (Login, Premium, Datei senden, Helfer-Tafel, KI-Studio, Admin, echter yt-dlp-Download-Motor)"
publish_to: "none"
version: 1.4.0+9

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  crypto: ^3.0.3
  url_launcher: ^6.2.6
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  open_filex: ^4.5.0
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
