/// 🌐 Bewusst im selben Stil wie das T-Dict der Desktop-App gehalten
/// (main.py) — gleiche Keys, gleiche Formulierungen, damit App und
/// Desktop-Version sich wie EIN Produkt anfühlen. Phase 1 deckt nur die
/// Login-/Verifizierungs-Screens ab; weitere Keys kommen mit den
/// nächsten Features dazu.
class AppStrings {
  final Map<String, String> _de = {
    'welcome': 'Willkommen',
    'create_account': 'Konto erstellen',
    'login': 'Anmelden',
    'email': 'E-Mail',
    'password': 'Passwort',
    'register': 'Registrieren',
    'have_account': 'Schon ein Konto? Anmelden',
    'no_account': 'Noch kein Konto? Registrieren',
    'forgot_password': 'Passwort vergessen?',
    'invalid_email': 'Bitte eine gültige E-Mail-Adresse eingeben.',
    'pw_too_short': 'Das Passwort muss mindestens 4 Zeichen haben.',
    'wrong_login': 'E-Mail oder Passwort ist falsch.',
    'user_exists': 'Für diese E-Mail existiert bereits ein Konto.',
    'checking_account': 'Konto wird geprüft...',
    'no_backend': 'Kein Server erreichbar — bitte Internetverbindung prüfen.',
    'verify_title': '✉️ E-Mail bestätigen',
    'verify_sending': 'Code wird gesendet...',
    'verify_sent': 'Wir haben einen 6-stelligen Code gesendet an:',
    'verify_code_ph': '6-stelliger Code',
    'verify_button': 'Bestätigen',
    'verify_resend': 'Code erneut senden',
    'verify_cancel': 'Abbrechen / abmelden',
    'verify_wrong': 'Der Code ist falsch.',
    'verify_expired': 'Der Code ist abgelaufen — bitte fordere einen neuen an.',
    'spam_hint_btn': '📥 Code nicht angekommen? Spam-Ordner prüfen',
    'spam_hint_title': 'Code nicht gefunden?',
    'spam_hint_text':
        'Kein Code in deinem Postfach? So findest du ihn meistens doch noch:\n\n'
        '📁 Schau in deinem Spam-/Junk-Ordner nach — Verifizierungs-E-Mails landen dort besonders oft.\n'
        '✅ Markiere die E-Mail als "Kein Spam", damit zukünftige Codes direkt im Posteingang landen.\n'
        '⏱️ Manchmal dauert es 1–2 Minuten, bis die E-Mail ankommt.\n'
        '✍️ Prüfe, ob deine E-Mail-Adresse oben richtig geschrieben ist.\n'
        '🔄 Falls nichts hilft: Nutze unten "Code erneut senden".',
    'forgot_title': '🔑 Passwort vergessen',
    'forgot_desc':
        'Gib deine E-Mail ein — wir schicken dir einen Bestätigungscode, mit dem du ein neues Passwort vergeben kannst.',
    'forgot_send_code': 'Code senden',
    'forgot_new_pw_ph': 'Neues Passwort',
    'forgot_confirm_btn': 'Passwort setzen',
    'forgot_back': 'Zurück zum Login',
    'forgot_code_sent': '✓ Code gesendet an',
    'forgot_no_account': 'Für diese E-Mail existiert kein Konto.',
    'forgot_ok': 'Passwort geändert! Du wirst weitergeleitet...',
    'contact_fail': 'Verbindung fehlgeschlagen — bitte später erneut versuchen.',
    'home_title': 'Downloader<3',
    'nav_download': 'Download',
    'nav_premium': 'Premium',
    'nav_settings': 'Einstellungen',
    'coming_soon_title': 'Kommt bald 🚧',
    'coming_soon_desc':
        'Dieser Bereich wird in einer der nächsten Android-Updates ergänzt — genau wie in der Windows-App, Schritt für Schritt.',
    'premium_active': '⭐ Premium aktiv',
    'premium_inactive': 'Kein Premium aktiv',
    'premium_until': 'Gültig bis',
    'premium_forever': 'Für immer',
    'redeem_code': 'Code einlösen',
    'code_placeholder': 'z. B. DL-A1B2-C3D4',
    'redeem': 'Einlösen',
    'buy_premium': 'Premium kaufen',
    'buy_premium_desc': 'Öffnet die Bezahlseite im Browser (PayPal). Nutze exakt diese E-Mail beim Bezahlen.',
    'premium_feedback': 'Probleme oder Feedback?',
    'code_ok': 'Code eingelöst — Premium ist aktiviert! 🎉',
    'code_bad': 'Code ist ungültig oder wurde schon benutzt.',
    'logout': 'Abmelden',
    'update_available': 'Update verfügbar',
    'update_now': 'Jetzt aktualisieren',
    'update_later': 'Später',
    'up_to_date': 'Du hast bereits die neueste Version.',
    'nav_sendfile': 'Datei senden',
    'nav_helper': 'Helfer',
    'nav_ai': 'KI-Studio',
    'nav_admin': 'Admin',
    'sendfile_title': 'Datei per E-Mail senden',
    'sendfile_intro': 'Schick ein Video, Bild, Musikstück oder sonst irgendetwas direkt per E-Mail.',
    'sendfile_premium_locked': 'Dateien per E-Mail versenden ist ein Premium-Feature. Hol dir Premium, um Dateien direkt aus der App zu verschicken.',
    'sendfile_pick_file': 'Datei auswählen',
    'sendfile_no_file': 'Keine Datei ausgewählt',
    'sendfile_recipient': 'Empfänger-E-Mail',
    'sendfile_message': 'Nachricht (optional)',
    'sendfile_send_btn': 'Senden',
    'sendfile_sending': 'Wird gesendet...',
    'sendfile_sent': 'Gesendet! 🎉',
    'sendfile_fail': 'Senden fehlgeschlagen',
    'sendfile_too_big': 'Diese Datei ist auf dem Handy leider zu groß (Limit: 6 MB) — für größere Dateien nutz aktuell bitte die Windows-App.',
    'sendfile_need_file': 'Bitte erst eine Datei auswählen.',
    'helper_title': '🤝 Helfer-Ehrentafel',
    'helper_desc': 'Alle Helfer, die sich freiwillig für die öffentliche Ehrentafel entschieden haben.',
    'helper_only_for_helpers': 'Dieser Bereich ist nur für Helfer-Konten sichtbar.',
    'helper_your_name': 'Dein Anzeigename',
    'helper_name_ph': 'z. B. dein Spitzname (max. 24 Zeichen)',
    'helper_set_btn': 'Anzeigenamen setzen',
    'helper_remove_btn': '🗑 Anzeigenamen entfernen',
    'helper_removed': 'Anzeigename entfernt.',
    'helper_saved': 'Gespeichert! 🎉',
    'helper_name_too_long': 'Der Name darf maximal 24 Zeichen lang sein.',
    'helper_create_code_btn': 'Eigenen Geschenk-Code erstellen (alle 2 Wochen)',
    'helper_code_created': 'Code erstellt:',
    'helper_cooldown': 'Noch nicht wieder möglich — bitte warte',
    'ai_title': '🎨 KI-Studio',
    'ai_text_tab': 'Text',
    'ai_image_tab': 'Bild',
    'ai_video_tab': 'Video',
    'ai_prompt_ph': 'Was soll die KI erstellen?',
    'ai_generate_btn': 'Erstellen',
    'ai_generating': 'Wird erstellt...',
    'ai_video_generating': 'Video wird erstellt (kann einige Minuten dauern)...',
    'ai_fail': 'Erstellen fehlgeschlagen',
    'ai_premium_locked': 'Das KI-Studio ist ein Premium-Feature.',
    'admin_title': '👑 Admin',
    'admin_unlock_desc': 'Owner-Passwort eingeben, um den Admin-Bereich freizuschalten.',
    'admin_owner_pw_ph': 'Owner-Passwort',
    'admin_unlock_btn': 'Freischalten',
    'admin_wrong_pw': 'Falsches Passwort.',
    'admin_grant_title': 'Premium schenken',
    'admin_email_ph': 'E-Mail-Adresse',
    'admin_days_ph': 'Tage (leer = für immer)',
    'admin_grant_btn': 'Schenken',
    'admin_revoke_btn': 'Premium entziehen',
    'admin_delete_btn': 'Konto löschen',
    'admin_make_helper_btn': 'Zum Helfer machen',
    'admin_unmake_helper_btn': 'Helfer zurückstufen',
    'admin_create_code_btn': 'Geschenk-Code erstellen',
    'admin_new_code_label': 'Neuer Code',
    'admin_copy_code': 'Kopieren',
    'admin_code_copied': 'Code kopiert! 📋',
    'admin_accounts_title': 'Alle Konten',
    'admin_load_accounts': 'Konten laden',
    'admin_ok': 'Erledigt! ✓',
    'settings_title': 'Einstellungen',
    'settings_accent': 'Akzentfarbe',
    'settings_check_update': 'Nach Updates suchen',
    'settings_visit_website': 'Webseite besuchen',
    'settings_contact_title': 'Kontaktiere uns — Probleme oder Feedback?',
    'settings_contact_msg_ph': 'Deine Nachricht...',
    'settings_contact_send': 'Nachricht senden',
    'settings_contact_sent': 'Nachricht gesendet! 🎉',
    'download_title': 'Herunterladen',
    'download_url_ph': 'Link einfügen (YouTube, TikTok, Instagram, ...)',
    'download_not_ready_title': 'Noch nicht verfügbar 🚧',
    'download_not_ready_desc': 'Der eigentliche Download-Motor (yt-dlp) braucht eine eigene native Anbindung fürs Handy — das ist der letzte große Baustein und kommt als eigene, sauber getestete Runde. Alles andere in der App funktioniert schon jetzt echt, gegen denselben Server wie die Windows-App.',
    'favorites': 'Favoriten',
    'favorite_url_ph': 'Link (URL)',
    'favorite_name_ph': 'Name (optional)',
    'no_favorites': 'Noch keine Favoriten gespeichert.',
    'add_favorite': 'Hinzufügen',
    'favorite_url_missing': 'Bitte zuerst einen Link eingeben.',
    'history': 'Letzte Downloads',
    'history_search_ph': '🔍 Verlauf durchsuchen...',
    'history_no_match': 'Keine Treffer.',
    'history_empty': 'Noch keine abgeschlossenen Downloads.',
    'open_folder': 'Ordner öffnen',
  };

  final Map<String, String> _en = {
    'welcome': 'Welcome',
    'create_account': 'Create account',
    'login': 'Log in',
    'email': 'Email',
    'password': 'Password',
    'register': 'Register',
    'have_account': 'Already have an account? Log in',
    'no_account': "Don't have an account? Register",
    'forgot_password': 'Forgot password?',
    'invalid_email': 'Please enter a valid email address.',
    'pw_too_short': 'Password must be at least 4 characters.',
    'wrong_login': 'Email or password is incorrect.',
    'user_exists': 'An account already exists for this email.',
    'checking_account': 'Checking account...',
    'no_backend': 'No server reachable — please check your internet connection.',
    'verify_title': '✉️ Verify your email',
    'verify_sending': 'Sending code...',
    'verify_sent': 'We sent a 6-digit code to:',
    'verify_code_ph': '6-digit code',
    'verify_button': 'Verify',
    'verify_resend': 'Resend code',
    'verify_cancel': 'Cancel / log out',
    'verify_wrong': 'That code is incorrect.',
    'verify_expired': 'That code has expired — please request a new one.',
    'spam_hint_btn': "📥 Code not showing up? Check your spam folder",
    'spam_hint_title': "Can't find your code?",
    'spam_hint_text':
        "No code in your inbox? Here's how to usually find it anyway:\n\n"
        '📁 Check your Spam/Junk folder — verification emails end up there a lot.\n'
        '✅ Mark the email as "Not spam" so future codes land straight in your inbox.\n'
        '⏱️ It can sometimes take 1–2 minutes for the email to arrive.\n'
        '✍️ Double-check the email address above is spelled correctly.\n'
        '🔄 Still nothing? Use "Resend code" below.',
    'forgot_title': '🔑 Forgot password',
    'forgot_desc':
        "Enter your email — we'll send a verification code you can use to set a new password.",
    'forgot_send_code': 'Send code',
    'forgot_new_pw_ph': 'New password',
    'forgot_confirm_btn': 'Set password',
    'forgot_back': 'Back to login',
    'forgot_code_sent': '✓ Code sent to',
    'forgot_no_account': 'No account exists for this email.',
    'forgot_ok': 'Password changed! Redirecting...',
    'contact_fail': 'Connection failed — please try again later.',
    'home_title': 'Downloader<3',
    'nav_download': 'Download',
    'nav_premium': 'Premium',
    'nav_settings': 'Settings',
    'coming_soon_title': 'Coming soon 🚧',
    'coming_soon_desc':
        'This section will be added in one of the next Android updates — just like on the Windows app, step by step.',
    'premium_active': '⭐ Premium active',
    'premium_inactive': 'No active premium',
    'premium_until': 'Valid until',
    'premium_forever': 'Forever',
    'redeem_code': 'Redeem code',
    'code_placeholder': 'e.g. DL-A1B2-C3D4',
    'redeem': 'Redeem',
    'buy_premium': 'Buy Premium',
    'buy_premium_desc': 'Opens the payment page in your browser (PayPal). Use exactly this email when paying.',
    'premium_feedback': 'Issues or feedback?',
    'code_ok': 'Code redeemed — Premium is active! 🎉',
    'code_bad': 'Code is invalid or already used.',
    'logout': 'Log out',
    'update_available': 'Update available',
    'update_now': 'Update now',
    'update_later': 'Later',
    'up_to_date': "You're already on the latest version.",
    'nav_sendfile': 'Send file',
    'nav_helper': 'Helper',
    'nav_ai': 'AI Studio',
    'nav_admin': 'Admin',
    'sendfile_title': 'Send a file by email',
    'sendfile_intro': 'Send a video, image, song, or anything else directly by email.',
    'sendfile_premium_locked': 'Sending files by email is a Premium feature. Get Premium to send files directly from the app.',
    'sendfile_pick_file': 'Choose file',
    'sendfile_no_file': 'No file selected',
    'sendfile_recipient': "Recipient's email",
    'sendfile_message': 'Message (optional)',
    'sendfile_send_btn': 'Send',
    'sendfile_sending': 'Sending...',
    'sendfile_sent': 'Sent! 🎉',
    'sendfile_fail': 'Failed to send',
    'sendfile_too_big': "Sorry, this file is too large on mobile (limit: 6 MB) — for bigger files please use the Windows app for now.",
    'sendfile_need_file': 'Please choose a file first.',
    'helper_title': '🤝 Helper honor board',
    'helper_desc': 'All helpers who opted in to the public honor board.',
    'helper_only_for_helpers': 'This section is only visible to helper accounts.',
    'helper_your_name': 'Your display name',
    'helper_name_ph': 'e.g. your nickname (max. 24 characters)',
    'helper_set_btn': 'Set display name',
    'helper_remove_btn': '🗑 Remove display name',
    'helper_removed': 'Display name removed.',
    'helper_saved': 'Saved! 🎉',
    'helper_name_too_long': 'The name can be at most 24 characters long.',
    'helper_create_code_btn': 'Create your own gift code (every 2 weeks)',
    'helper_code_created': 'Code created:',
    'helper_cooldown': 'Not available again yet — please wait',
    'ai_title': '🎨 AI Studio',
    'ai_text_tab': 'Text',
    'ai_image_tab': 'Image',
    'ai_video_tab': 'Video',
    'ai_prompt_ph': 'What should the AI create?',
    'ai_generate_btn': 'Generate',
    'ai_generating': 'Generating...',
    'ai_video_generating': 'Generating video (can take several minutes)...',
    'ai_fail': 'Generation failed',
    'ai_premium_locked': 'AI Studio is a Premium feature.',
    'admin_title': '👑 Admin',
    'admin_unlock_desc': 'Enter the owner password to unlock the admin area.',
    'admin_owner_pw_ph': 'Owner password',
    'admin_unlock_btn': 'Unlock',
    'admin_wrong_pw': 'Wrong password.',
    'admin_grant_title': 'Gift Premium',
    'admin_email_ph': 'Email address',
    'admin_days_ph': 'Days (empty = forever)',
    'admin_grant_btn': 'Gift',
    'admin_revoke_btn': 'Revoke Premium',
    'admin_delete_btn': 'Delete account',
    'admin_make_helper_btn': 'Promote to helper',
    'admin_unmake_helper_btn': 'Demote helper',
    'admin_create_code_btn': 'Create gift code',
    'admin_new_code_label': 'New code',
    'admin_copy_code': 'Copy',
    'admin_code_copied': 'Code copied! 📋',
    'admin_accounts_title': 'All accounts',
    'admin_load_accounts': 'Load accounts',
    'admin_ok': 'Done! ✓',
    'settings_title': 'Settings',
    'settings_accent': 'Accent color',
    'settings_check_update': 'Check for updates',
    'settings_visit_website': 'Visit website',
    'settings_contact_title': 'Contact us — Issues or feedback?',
    'settings_contact_msg_ph': 'Your message...',
    'settings_contact_send': 'Send message',
    'settings_contact_sent': 'Message sent! 🎉',
    'download_title': 'Download',
    'download_url_ph': 'Paste a link (YouTube, TikTok, Instagram, ...)',
    'download_not_ready_title': 'Not available yet 🚧',
    'download_not_ready_desc': "The actual download engine (yt-dlp) needs its own native integration for mobile — that's the last big building block and is coming as its own, properly tested round. Everything else in the app already works for real, against the same server as the Windows app.",
    'favorites': 'Favorites',
    'favorite_url_ph': 'Link (URL)',
    'favorite_name_ph': 'Name (optional)',
    'no_favorites': 'No favorites saved yet.',
    'add_favorite': 'Add',
    'favorite_url_missing': 'Please enter a link first.',
    'history': 'Recent downloads',
    'history_search_ph': '🔍 Search history...',
    'history_no_match': 'No matches.',
    'history_empty': 'No completed downloads yet.',
    'open_folder': 'Open folder',
  };

  String lang;
  AppStrings(this.lang);

  String t(String key) {
    final map = lang == 'de' ? _de : _en;
    return map[key] ?? key;
  }
}
